/**
 * Every checked-in deployment manifest, keyed by chain id.
 *
 * Generated by scripts/generate-deployment-manifest.mjs from the contents of
 * this directory. Do not edit by hand: rerun the generator so the registry and
 * the JSON beside it cannot fall out of step.
 *
 * Empty is a valid state: it means no network has a reviewed deployment yet,
 * and the app reports every chain as unconfigured rather than guessing.
 */
import type { DeploymentManifest } from "@/lib/dollar/manifest";

import chain46630 from "./46630.json";

export const deploymentManifests: Readonly<Record<number, DeploymentManifest>> = {
  46630: chain46630 as DeploymentManifest,
};
