/**
 * Every checked-in deployment manifest, keyed by chain id.
 *
 * Regenerated by scripts/generate-deployment-manifest.mjs alongside the JSON it
 * imports, so adding a network is one command and one reviewable commit rather
 * than a hand-edited import list that can fall out of step with the directory.
 *
 * Empty is a valid state: it means no network has a reviewed deployment yet,
 * and the app will report every chain as unconfigured rather than guessing.
 */
import type { DeploymentManifest } from "@/lib/dollar/manifest";

export const deploymentManifests: Readonly<Record<number, DeploymentManifest>> = {};
